[book]
authors = ["Abhishek Kumar","Dhruv Bodani"]
language = "en"
multilingual = false
src = "book"
title = "Maya Docs"
description = "A book on all things maya"

[output.html]
theme = "book/theme"
git-repository-url = "https://github.com/LabsMaya/maya-zk-benchmarks"
default-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = true
level = 1

[output.html.playground]
runnable = false

[build]
build-dir = "target/book"
