#on:
#  push:
#    branches:
#      - *
#    tags:
#      - 'v*'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

name: Build and Publish Docker Image
jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: docker/setup-buildx-action@v2

    - name: Define docker image meta data tags
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          mayalabs/maya
        tags: |
          # Tag "git short sha" on all git events
          type=sha,prefix=

          # Tag "next" on git-push-to-main-branch events
          type=raw,value=next,event=branch,enable={{is_default_branch}}

          # Tag "latest" on git-tag events
          type=raw,value=latest,event=tag

          # Tag "$APP_VERSION" on git-push-to-branch events
          type=raw,value=${{ env.APP_VERSION }},event=branch

          # Tag "tag ref" on git-tag events
          type=ref,event=tag

#    - name: Login to Github container registry
#      uses: docker/login-action@v2
#      with:
#        registry: ghcr.io
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Dockerhub container registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          GITHUB_SHA=${{ github.sha }}
          GO_BUILD_FLAG=${{ env.GO_BUILD_FLAG }}
        tags: ${{ steps.meta.outputs.tags }}

    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short=7 ${{ github.sha }})
        echo "::set-output name=short_sha::$calculatedSha"
